### ISSUE TITLE
getting error after adding

### ISSUE THREAD

**Issue by sparkmobi** [fzyzcjy/flutter_smooth#150]
**Describe the bug**
i have tried to run smooth example app but i have got these errors

`../smooth/lib/src/infra/extra_event_dispatcher.dart:48:9: Error: No named parameter with the name 'filter'.
        filter: (entry) {
        ^^^^^^
../smooth/lib/src/infra/extra_event_dispatcher.dart:114:24: Error: The method 'readEnginePendingEventsAndClear' isn't defined for the class 'GestureBinding'.
 - 'GestureBinding' is from 'package:flutter/src/gestures/binding.dart' ('/F:/flutter/packages/flutter/lib/src/gestures/binding.dart').
Try correcting the name to the name of an existing method, or defining a method named 'readEnginePendingEventsAndClear'.
        gestureBinding.readEnginePendingEventsAndClear();
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../smooth/lib/src/infra/binding.dart:130:17: Error: Type 'HitTestEntryFilter' not found.
      {required HitTestEntryFilter? filter}) {
                ^^^^^^^^^^^^^^^^^^
../smooth/lib/src/infra/binding.dart:301:7: Error: Class 'WidgetsFlutterBinding with SmoothSchedulerBindingMixin, SmoothGestureBindingMixin with SmoothRendererBindingMixin' inherits multiple members named 'GestureBinding.dispatchEvent%RendererBinding.dispatchEvent%GestureBinding.dispatchEvent%RendererBinding.dispatchEvent%SmoothGestureBindingMixin.dispatchEvent' with incompatible signatures.
Try adding a declaration of 'GestureBinding.dispatchEvent%RendererBinding.dispatchEvent%GestureBinding.dispatchEvent%RendererBinding.dispatchEvent%SmoothGestureBindingMixin.dispatchEvent' to 'WidgetsFlutterBinding with SmoothSchedulerBindingMixin, SmoothGestureBindingMixin with SmoothRendererBindingMixin'.
class SmoothWidgetsFlutterBinding extends WidgetsFlutterBinding
      ^
/F:/flutter/packages/flutter/lib/src/gestures/binding.dart:415:8: Context: This is one of the overridden members.
  void dispatchEvent(PointerEvent event, HitTestResult? hitTestResult) {
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
/F:/flutter/packages/flutter/lib/src/rendering/binding.dart:328:8: Context: This is one of the overridden members.
  void dispatchEvent(PointerEvent event, HitTestResult? hitTestResult) {
       ^^^^^^^^^^^^^
../smooth/lib/src/infra/binding.dart:301:7: Error: Class 'WidgetsFlutterBinding with SmoothSchedulerBindingMixin, SmoothGestureBindingMixin, SmoothRendererBindingMixin with SmoothWidgetsBindingMixin' inherits multiple members named 'GestureBinding.dispatchEvent%RendererBinding.dispatchEvent%GestureBinding.dispatchEvent%RendererBinding.dispatchEvent%SmoothGestureBindingMixin.dispatchEvent%RendererBinding.dispatchEvent' with incompatible signatures.
Try adding a declaration of 'GestureBinding.dispatchEvent%RendererBinding.dispatchEvent%GestureBinding.dispatchEvent%RendererBinding.dispatchEvent%SmoothGestureBindingMixin.dispatchEvent%RendererBinding.dispatchEvent' to 'WidgetsFlutterBinding with SmoothSchedulerBindingMixin, SmoothGestureBindingMixin, SmoothRendererBindingMixin with SmoothWidgetsBindingMixin'.
class SmoothWidgetsFlutterBinding extends WidgetsFlutterBinding
      ^
/F:/flutter/packages/flutter/lib/src/gestures/binding.dart:415:8: Context: This is one of the overridden members.
  void dispatchEvent(PointerEvent event, HitTestResult? hitTestResult) {
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
/F:/flutter/packages/flutter/lib/src/gestures/binding.dart:415:8: Context: This is one of the overridden members.
  void dispatchEvent(PointerEvent event, HitTestResult? hitTestResult) {
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../smooth/lib/src/infra/binding.dart:60:9: Error: The method 'adjustForEpoch' isn't defined for the class 'SmoothSchedulerBindingMixin'.
 - 'SmoothSchedulerBindingMixin' is from 'package:smooth/src/infra/binding.dart' ('../smooth/lib/src/infra/binding.dart').
Try correcting the name to the name of an existing method, or defining a method named 'adjustForEpoch'.
        adjustForEpoch(rawTimeStamp ?? currentSystemFrameTimeStamp));
        ^^^^^^^^^^^^^^
../smooth/lib/src/infra/binding.dart:130:17: Error: 'HitTestEntryFilter' isn't a type.
      {required HitTestEntryFilter? filter}) {
                ^^^^^^^^^^^^^^^^^^
../smooth/lib/src/infra/binding.dart:140:49: Error: No named parameter with the name 'filter'.
      super.dispatchEvent(event, hitTestResult, filter: filter);
                                                ^^^^^^
../smooth/lib/src/infra/binding.dart:169:9: Error: No named parameter with the name 'fallbackVsyncTargetTime'.
        fallbackVsyncTargetTime: effectiveFallbackVsyncTargetTime,
        ^^^^^^^^^^^^^^^^^^^^^^^
../smooth/lib/src/infra/binding.dart:217:11: Error: No named parameter with the name 'forceDirectlyCallNextVsyncTargetTime'.
          forceDirectlyCallNextVsyncTargetTime:
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../smooth/lib/src/infra/proxy.dart:13:53: Error: The getter 'nodesNeedingPaint' isn't defined for the class 'PipelineOwner'.
 - 'PipelineOwner' is from 'package:flutter/src/rendering/object.dart' ('/F:/flutter/packages/flutter/lib/src/rendering/object.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'nodesNeedingPaint'.
  List<RenderObject> get nodesNeedingPaint => inner.nodesNeedingPaint;
                                                    ^^^^^^^^^^^^^^^^^
../smooth/lib/src/infra/proxy.dart:141:27: Error: No named parameter with the name 'fallbackVsyncTargetTime'.
      inner.render(scene, fallbackVsyncTargetTime: fallbackVsyncTargetTime);
                          ^^^^^^^^^^^^^^^^^^^^^^^
../smooth/lib/src/infra/proxy.dart:259:11: Error: No named parameter with the name 'forceDirectlyCallNextVsyncTargetTime'.
          forceDirectlyCallNextVsyncTargetTime:
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../smooth/lib/src/infra/auxiliary_tree_pack.dart:36:27: Error: Method not found: 'TickerRegistry'.
  final _tickerRegistry = TickerRegistry();
                          ^^^^^^^^^^^^^^
../smooth/lib/src/infra/auxiliary_tree_pack.dart:58:14: Error: The method 'TickerRegistryInheritedWidget' isn't defined for the class 'AuxiliaryTreePack'.
 - 'AuxiliaryTreePack' is from 'package:smooth/src/infra/auxiliary_tree_pack.dart' ('../smooth/lib/src/infra/auxiliary_tree_pack.dart').
Try correcting the name to the name of an existing method, or defining a method named 'TickerRegistryInheritedWidget'.
      child: TickerRegistryInheritedWidget(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../smooth/lib/src/infra/auxiliary_tree_pack.dart:181:26: Error: Unexpected type 'invalid-type' of a spread.  Expected 'dynamic' or an Iterable.
      ..._tickerRegistry.tickers,
                         ^
../smooth/lib/src/infra/auxiliary_tree_pack.dart:225:16: Error: Setter not found: 'debugActiveLayout'.
  RenderObject.debugActiveLayout = null;
               ^^^^^^^^^^^^^^^^^
../smooth/lib/src/infra/auxiliary_tree_pack.dart:229:18: Error: Setter not found: 'debugActiveLayout'.
    RenderObject.debugActiveLayout = oldDebugActiveLayout;
                 ^^^^^^^^^^^^^^^^^
../smooth/lib/src/infra/actor.dart:135:9: Error: No named parameter with the name 'fallbackVsyncTargetTime'.
        fallbackVsyncTargetTime:
        ^^^^^^^^^^^^^^^^^^^^^^^
../smooth/lib/src/infra/actor.dart:143:34: Error: The method 'notifyIdle' isn't defined for the class 'PlatformDispatcher'.
 - 'PlatformDispatcher' is from 'dart:ui'.
Try correcting the name to the name of an existing method, or defining a method named 'notifyIdle'.
      binding.platformDispatcher.notifyIdle(
                                 ^^^^^^^^^^
../smooth/lib/src/drop_in/page_route/page_routes.dart:77:3: Error: The superclass, 'PageRouteBuilder with SmoothPageRouteMixin<T>', has no unnamed constructor that takes no arguments.
  SmoothPageRouteBuilder({
  ^^^^^^^^^^^^^^^^^^^^^^
../smooth/lib/src/drop_in/page_route/page_routes.dart:104:11: Error: No named parameter with the name 'allowSnapshotting'.
          allowSnapshotting: false,
          ^^^^^^^^^^^^^^^^^
../smooth/lib/src/drop_in/list_view/controller.dart:71:25: Error: The getter 'controller' isn't defined for the class '_SmoothBallisticScrollActivity'.
 - '_SmoothBallisticScrollActivity' is from 'package:smooth/src/drop_in/list_view/controller.dart' ('../smooth/lib/src/drop_in/list_view/controller.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'controller'.
                      ?.controller.lastElapsedDuration?.inMicroseconds ??
                        ^^^^^^^^^^
../smooth/lib/src/drop_in/list_view/controller.dart:140:3: Error: The superclass, 'BallisticScrollActivity', has no unnamed constructor that takes no arguments.
  _SmoothBallisticScrollActivity.raw(
  ^^^
../smooth/lib/src/drop_in/list_view/shift.dart:352:36: Error: The getter 'startTime' isn't defined for the class 'Ticker'.
 - 'Ticker' is from 'package:flutter/src/scheduler/ticker.dart' ('/F:/flutter/packages/flutter/lib/src/scheduler/ticker.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'startTime'.
    final tickTimeStamp = _ticker!.startTime! + selfTickerElapsed;
                                   ^^^^^^^^^
../smooth/lib/src/drop_in/list_view/shift.dart:356:59: Error: The getter 'startTime' isn't defined for the class 'Ticker'.
 - 'Ticker' is from 'package:flutter/src/scheduler/ticker.dart' ('/F:/flutter/packages/flutter/lib/src/scheduler/ticker.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'startTime'.
    final ballisticTickerStartTime = info.ballisticTicker.startTime;
                                                          ^^^^^^^^^
../smooth/lib/src/drop_in/list_view/list_view.dart:34:28: Error: The argument type 'Widget? Function(BuildContext, int)' can't be assigned to the parameter type 'Widget Function(BuildContext, int)' because 'Widget?' is nullable and 'Widget' isn't.
 - 'Widget' is from 'package:flutter/src/widgets/framework.dart' ('/F:/flutter/packages/flutter/lib/src/widgets/framework.dart').
 - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('/F:/flutter/packages/flutter/lib/src/widgets/framework.dart').
              itemBuilder: itemBuilder,
                           ^
../smooth/lib/src/drop_in/list_view/list_view.dart:116:22: Error: A value of type 'Widget?' can't be returned from a function with return type 'Widget' because 'Widget?' is nullable and 'Widget' isn't.
 - 'Widget' is from 'package:flutter/src/widgets/framework.dart' ('/F:/flutter/packages/flutter/lib/src/widgets/framework.dart').
              return widget.itemBuilder(context, index - 1);`

**To Reproduce**
1. open example project
2. Click on run
3. click on run tab

**Comment by fzyzcjy** [comment]
Yes, it requires a custom flutter engine and framework build currently :/ Track this page https://cjycode.com/flutter_smooth/insight/status to see when PRs are merged to flutter

**Comment by fzyzcjy** [comment]
> Also make a SmoothCupertinoPageRoute

Feel free to PR :) that should be quite easy by mimicking SmoothMaterialPageRoute

**Comment by sparkmobi** [comment]
okay, thank you so much

**Comment by fzyzcjy** [comment]
You are welcome :)
