### ISSUE TITLE
compile flutter engine ref by flutter_smooth always get  Error, No named parameter with the name 'fallbackVsyncTargetTime'.

### ISSUE THREAD

**Issue by vickyleu** [fzyzcjy/flutter_smooth#154]
**Is your feature request related to a problem? Please describe.**
$./flutter/tools/gn --unoptimized --no-goma --no-prebuilt-dart-sdk
$ ninja -C out/host_debug_unopt

in engine/src/out/host_debug_unopt/gen/dart-pkg/sky_engine/lib/ui/window.dart 265 line is still as
`void render(Scene scene) => _render(scene);` 

**Describe the solution you'd like**
how do i compile engine/lib/ui/window.dart into dart sdk? i search google for long time, but no one explain engine compile with dart sdk

**Comment by fzyzcjy** [comment]
Please use framework and engine in my branch :)

**Comment by vickyleu** [comment]
@fzyzcjy Yes, I am using your engine and framework, when i compiled engine and set sky_engine to local path in pubspec.yaml ,but the dart sdk stills not work, I compared host_debug_unopt, the sky_engine code is not replaced correctly

**Comment by fzyzcjy** [comment]
IIRC I hardcoded sky engine debug override to my local path. Have you changed that?

**Comment by vickyleu** [comment]
@fzyzcjy i changed it
dependency_overrides:

  sky_engine:
    path: /Volumes/extra/Github/engine/src/out/android_debug_unopt/gen/dart-pkg/sky_engine

**Comment by fzyzcjy** [comment]
`--no-prebuilt-dart-sdk`

wait, we should use the prebuilt dart

**Comment by vickyleu** [comment]
yes , add `--no-prebuilt-dart-sdk` when ./flutter/tools/gn

**Comment by vickyleu** [comment]
remove it also not build sky_engine correctly, throw No named parameter

**Comment by vickyleu** [comment]
I have retried eight times for various parameter configurations, re-clone, re-sync, re-download

**Comment by vickyleu** [comment]
step:
`git clone git@github.com:fzyzcjy/engine.git`

`cd  engine`

`git checkout flutter_smooth`

`vim .gclient`
`
solutions = [
  {
    "managed": False,
    "name": "src/flutter",
    "url": "git@github.com:fzyzcjy/engine.git@465ccd29740625d20ab0cdf2529a9dda19824e99",
    "custom_deps": {},
    "deps_file": "DEPS",
    "safesync_url": "",
  },
]
`
`gclient sync`

`cd src`

`./flutter/tools/gn --unoptimized`

`ninja -C out/host_debug_unopt`

**Comment by vickyleu** [comment]
Is there anything I'm missing in these steps? @fzyzcjy

**Comment by vickyleu** [comment]
`Building flutter tool...
[✓] Flutter (Channel master, 3.5.0-9.0.pre.3, on macOS 12.6 21G115 darwin-arm64, locale zh-Hans-CN)
    • Flutter version 3.5.0-9.0.pre.3 on channel master at /Volumes/extra/flutter
    • Upstream repository https://github.com/fzyzcjy/flutter.git
    • FLUTTER_GIT_URL = https://github.com/fzyzcjy/flutter.git
    • Framework revision 2ea90eaed2 (6 days ago), 2022-10-17 19:13:49 -0400
    • Engine revision 465ccd2974
    • Dart version 2.19.0 (build 2.19.0-314.0.dev)
    • DevTools version 2.18.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Volumes/extra/Android/sdk/
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Volumes/extra/Android/sdk/
    • Java binary at: /Users/vickyleu/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9123335/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Users/vickyleu/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9123335/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.6 21G115 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 106.0.5249.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
`

**Comment by fzyzcjy** [comment]
maybe check whether your local code has https://github.com/fzyzcjy/engine/blob/7e646656db8ac82d8436942e9f8e738999b0bdc4/lib/ui/window.dart#L265 this argument?

**Comment by fzyzcjy** [comment]
btw sky_engine is from Flutter engine, not from Dart sdk

**Comment by fzyzcjy** [comment]
I am indeed not an expert in compiling flutter itself... :/

**Comment by vickyleu** [comment]
The engine under the flutter_smooth branch has this part of the code, and the compile-time branch is also the smooth branch, but it will not be exported to sky_engine

**Comment by fzyzcjy** [comment]
very weird... is it cache problem? (I guess no since you clear it?)

**Comment by vickyleu** [comment]
I can confirm that it is not a cache problem. I deleted all files, cloned and recompiled.

**Comment by fzyzcjy** [comment]
Hmm, what about this: skip this error, and try whether it can compile on a real android device?

**Comment by vickyleu** [comment]
I know why, src/flutter is a copy of the engine root directory,so after switching to flutter-smooth in the engine root directory, gclient sync, and also need to switch the src/flutter directory to flutter-smooth and gclient sync....

**Comment by fzyzcjy** [comment]
ah, seems we should not modify engine root dir? iirc that is build_root instead of real code related to flutter

**Comment by tijanirf** [comment]
> git clone git@github.com:fzyzcjy/engine.git

Hi @vickyleu , sorry for necroposting. Could you update these steps after you solved the issue? Thank you
