### ISSUE TITLE
Disable the deliberate delay

### ISSUE THREAD

**Issue by theniceboy** [fzyzcjy/flutter_smooth#158]
How to disable the deliberate delay mentioned in https://cjycode.com/flutter_smooth/design/infra/gesture/delay ?

Thanks!

**Comment by fzyzcjy** [comment]
That probably is more than simply disabling it. Looking at the section of doc, we can see it is there to avoid inconsistency. But I guess it should be able to be disabled. Feel free to PR!

**Comment by theniceboy** [comment]
@fzyzcjy Unfortunately I won’t be able to create a PR. Could you give me some more instructions to how to disable it please? Thank you!

**Comment by fzyzcjy** [comment]
@theniceboy 

> Unfortunately I won’t be able to create a PR

Not sure what is happening. do you mean Your github account has some problem?

**Comment by theniceboy** [comment]
@fzyzcjy Well I don’t have any knowledge about the flutter framework and to be honest that is way to complex for my understanding. So I won’t be able to file a pull request. I doubt most people will… not because I don’t want to, but I can’t. Not anytime soon.

**Comment by fzyzcjy** [comment]
@theniceboy Well that is a problem :/ It should be more than a flag to disable it. Indeed, need to consider a bit how the change affects other parts of the system. I have not examined the details yet (quite busy now), but the rough idea looks feasible IMHO.

**Comment by theniceboy** [comment]
@fzyzcjy Sounds good. Let me know when you get to look at it. Currently the one frame jank issue is the only issue I see in Flutter that’s related to jank. I hope this package will be able to solve it.

**Comment by theniceboy** [comment]
Any update on this? @fzyzcjy

**Comment by fzyzcjy** [comment]
Not checked yet, but again you are welcomed to learn more about flutter and check that :)

**Comment by theniceboy** [comment]
To be honest it's not really realistic for a normal developer like me to dig into the Flutter framework. Since you have the knowledge, it's best for you to provide some help, and that will be very appreciated! Thanks! @fzyzcjy

**Comment by fzyzcjy** [comment]
> To be honest it's not really realistic for a normal developer like me to dig into the Flutter framework.

Don't think it is impossible - every expert in every field must have been a newlearner in the beginning. 

As a first step, there are some book chapters discussing flutter internals (since I see you are Chinese, this one looks good: https://book.flutterchina.club/chapter14/flutter_ui_system.html). It is indeed not that hard :)

I will try to find some time to look at it. But as said before, I have my own work to do and need to firstly make the PRs for flutter_smooth.

**Comment by fzyzcjy** [comment]
> To be honest it's not really realistic for a normal developer like me to dig into the Flutter framework.

Don't think it is impossible - every expert in every field must have been a newlearner in the beginning. 

As a first step, there are some book chapters discussing flutter internals (since I see you are Chinese, this one looks good: https://book.flutterchina.club/chapter14/flutter_ui_system.html written by @wendux). It is indeed not that hard :)

I will try to find some time to look at it. But as said before, I have my own work to do and need to firstly make the PRs for flutter_smooth.

**Comment by theniceboy** [comment]
Don't think you got the point haha😄 Difficulty isn't the problem. The problem is that it's not exactly cost-effective for me to work on this (lol), since it's not me but you that's working on your package. Getting this issue resolved gets me marginal benefits compared to the time that's required to put in. If you are not able to help, it's totally okay.

Good luck with the PRs!

**Comment by fzyzcjy** [comment]
I see. But open source is just like this - I do not have infinite time and energy to solve all problems, and since it is open sourced, people can freely contribute :)

**Comment by theniceboy** [comment]
I really want to believe that haha😄 But based on the contribution I see on this package... It's gonna be hard.

I do respect your github contribution chart though. You almost have infinite time and energy😄

**Comment by fzyzcjy** [comment]
> But based on the contribution I see on this package... It's gonna be hard.

I agree. But anyway, this package is even not production ready yet - because the flutter PRs have not been merged. So hopefully it will be different in the future.

> I do respect your github contribution chart though. You almost have infinite time and energy😄

No that just because I prefer to separate commit into tiny parts (you can see the style from my open source libs).

But yes, I do programming 7 days a week.

**Comment by theniceboy** [comment]
瑞思拜 bro

**Comment by fzyzcjy** [comment]
Thanks :) 

(Btw please speak english in github since it is read by people in the world)

**Comment by theniceboy** [comment]
yessir

**Comment by theniceboy** [comment]
其实。。。我觉得没关系。。。两个中国人在这儿打英文，心里还是感觉有点别扭。（还这么多语法错误😂）

非常感谢你对Flutter的贡献。我看你的PR有不少困难，希望你和团队接下来的讨论顺利吧。加油！

你要不介意的话要不加个联系方式？我在你的主页上没找到。我的邮箱在我的主页里。

**Comment by fzyzcjy** [comment]
> actually. . . I don't think it matters. . . Two Chinese people are typing English here, and I still feel a little awkward. (so many grammatical errors 😂)

It is not the problem of you, but instead the problem of the future readers. What do you feel when you go to a github repo and look at an issue that is important to you, only to find someone speaking languages that you have never learnt? :)

And as for grammar errors - IMHO it does not matter as long as everyone can understand the content.

> Thank you so much for your contribution to Flutter. I see that your PR has a lot of difficulties. I hope you and the team will have a smooth discussion next time. come on!

You are welcome. Btw it is *me* (one single individual developer), not a team.

> Would you like to add a contact if you don't mind? I didn't find it on your homepage. My email is on my homepage.

You can find me on github as well as Flutter discord :) I reply usually quite quickly.

**Comment by theniceboy** [comment]
哈哈2022年大家都有google翻译吧

**Comment by theniceboy** [comment]
不浪费你时间啦，加油加油

**Comment by fzyzcjy** [comment]
Thank you :)

**Comment by theniceboy** [comment]
不用谢～

**Comment by theniceboy** [comment]
哦哦你没太理解我的意思😂 我是说加油和Flutter团队交流

**Comment by fzyzcjy** [comment]
I see. Thanks :)
