### ISSUE TITLE
There are many files with errors (caused by using incorrect branch to compile)

### ISSUE THREAD

**Issue by MarkBurt** [fzyzcjy/flutter_smooth#175]
![image_2022-11-15_02-48-41](https://user-images.githubusercontent.com/54026540/201741439-b5249b69-4842-45ba-8200-138d37e89062.png)

**Comment by fzyzcjy** [comment]
As mentioned in doc, need to use custom framework and engine build :)

**Comment by fzyzcjy** [comment]
bump
