### ISSUE TITLE
Enabling issues on `charts` repo

### ISSUE THREAD

**Issue by deckerst** [fzyzcjy/flutter_smooth#187]
Sorry to open this issue in this repo but i didn't know how to contact you otherwise.

I'd like to open an issue on [your fork of `charts`](https://github.com/fzyzcjy/charts) but it seems issues are disabled for that repo. Could you please enable them?

**Comment by fzyzcjy** [comment]
Sure, done :)

**Comment by fzyzcjy** [comment]
Btw not sure why it was not opened, maybe github auto disable them for forked repo?

**Comment by deckerst** [comment]
I think it copies the settings from the original repo, no?

**Comment by fzyzcjy** [comment]
I don't know indeed, anyway that's not a problem :)
