### ISSUE TITLE
Current status

### ISSUE THREAD

**Issue by fzyzcjy** [fzyzcjy/flutter_smooth#59]
Please refer to

1. The doc https://cjycode.com/flutter_smooth/
2. ~~The project board https://github.com/users/fzyzcjy/projects/5~~ Just refer to issue section since some things are in issue but not in project: https://github.com/fzyzcjy/flutter_smooth/issues

**Comment by Erik0806** [comment]
First of all thank you for your great work.
The link does not work.

**Comment by fzyzcjy** [comment]
@Erik0806 Not a mistake - it was wrongly set to private (default permission?). I fixed it after seeing your comment :)

**Comment by Erik0806** [comment]
Wow that was fast. Thank you

**Comment by fzyzcjy** [comment]
You are welcome!

**Comment by bugrevealingbme** [comment]
What is the compatibility for 120fps?

**Comment by fzyzcjy** [comment]
It should work well.

But current code comes from my prototype which hardcode the number 60, so need to have some (trivial) PR and it will work well. this package definitely has no special limitation on 60!

**Comment by bugrevealingbme** [comment]
I wanted to try it in Flutter 3.3.4 but I guess a dev version is needed. By the way, it causes fps drops in ImageFilter.blur, would you consider doing a special work for blur? You are really good at this, thanks

**Comment by fzyzcjy** [comment]
Indeed a custom engine build: https://github.com/fzyzcjy/flutter_smooth/issues/150#issuecomment-1283276166

> By the way, it causes fps drops in ImageFilter.blur, would you consider doing a special work for blur

That seem to be *rasterizer* jank, which Flutter team is solving probably via the Impeller :)

**Comment by fzyzcjy** [comment]
added to readme, thus this issue is closed
