### ISSUE TITLE
Write an article discussing how it is implemented

### ISSUE THREAD

**Issue by fzyzcjy** [fzyzcjy/flutter_smooth#89]
Possible outline

* preemptRender
* Brake
* gesture subsystem
* how SmoothListView is implemented (also serve as an example to use SmoothBuilder)
* how SmoothMaterialPageRoute is implemented

**Comment by prasadsunny1** [comment]
Yes, everyone is asking. What is this sorcery?

**Comment by fzyzcjy** [comment]
@prasadsunny1 Wait for a few days ;) I am busy making PR and writing it

**Comment by FrizzleFur** [comment]
Just download code, I found that SmoothBuilder has a pack of AdapterInMainTreeWidget, which wrapper the child widget with a RemoveSubTreeWidget, and remove the sub tree when disposed. So, I guess, remove the subtree in  the appropriate time when UI changes (like scrolling、animation and so on), to render faster.

**Comment by fzyzcjy** [comment]
@FrizzleFur Nice guess, but that is not the magic ;) I am still polishing the article

**Comment by fzyzcjy** [comment]
https://cjycode.com/flutter_smooth/design/
