### ISSUE TITLE
Improve `SmoothListView.handleEnginePendingEvent` by triggering conditionally

### ISSUE THREAD

**Issue by fzyzcjy** [fzyzcjy/flutter_smooth#97]

**Comment by Erik0806** [comment]
Could it be possible to wrap the Smoothlistview in a Listener and then listen for pointerUpEvents?

**Comment by fzyzcjy** [comment]
* For pointer *move* events, already handle it well in PreemptRender mechanism
* For pointer up/down/whatever-fancy events, the Brake mechanism works well

Both are demonstrated in SmoothListView

anyway, you may not know those terms before I write down an article explaining the internals...

**Comment by fzyzcjy** [comment]
bump
